---
- hosts: all
  become: true
  tasks:
       
     - name: Install
       ansible.builtin.yum:
         name: 
            - mdadm
            - smartmontools 
            - hdparm 
            - gdisk
         state: present  

     - name: RAID 
       ansible.builtin.shell: mdadm --create --verbose /dev/md0 -l 1 -n 4 /dev/sd{b,c,d,e}
       

       

