---
- hosts: all
  become: true
  become_user: root
  tasks:

       
     - name: cd
       ansible.builtin.shell: cd /etc/yum.repos.d/

     - name: resume 
       ansible.builtin.shell: sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
       
     - name: resume repo
       ansible.builtin.shell: sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
       
     - name: update
       ansible.builtin.shell: yum update -y  

     - name: add repo
       ansible.builtin.shell: sudo yum install -y https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
       
     - name: install core
       ansible.builtin.shell: sudo yum --enablerepo elrepo-kernel install kernel-ml -y
       

         
     - name: reboot system 
       reboot: 
         msg: "reload"
         connect_timeout: 5
         reboot_timeout: 600
         post_reboot_delay: 30
         test_command: whoami






        

       
 
